# Generated by Django 4.2.5 on 2023-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambient', '0003_alter_dht22_device_name_alter_dht22_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht22',
            name='uvLevel',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
